import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "../ui/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy | Von Newman Atlas",
  description: "How Von Newman Atlas collects, uses and protects personal data in Nigeria.",
};

const sections: LegalSection[] = [
  { id: "scope", title: "Who this policy covers", body: <><p>This Privacy Policy explains how <strong>Von Newman Technology Consultant Limited</strong> (“Von Newman”, “we”, “us” or “our”) processes personal data through the Atlas website, learning-management system, content-management system, course library, administrator tools and related support services in Nigeria.</p><p>Atlas is designed mainly for organisations and their authorised learners, employees, contractors, administrators, instructors, assessors and managers. This policy should be read with our <a href="/terms">Terms of Service</a>, any customer order, and any Data Processing Agreement agreed with an organisation.</p></> },
  { id: "roles", title: "Our role and your organisation’s role", body: <><h3>Organisation-managed accounts</h3><p>When your employer, public body or institution creates or manages your Atlas account, it will generally determine why your workforce-learning data is used and act as the data controller. Von Newman will generally process that data on its documented instructions.</p><p>Your organisation may determine who receives an account, what learning is assigned, the administrators who can see progress, deadlines, reporting requirements and appropriate retention periods. Questions about an organisation’s use of your learning record should normally be directed to its administrator or privacy contact.</p><h3>When Von Newman is the controller</h3><p>We act as controller for our own website, customer relationships, platform security, support, service communications, billing, legal records, permitted marketing and product operations.</p></> },
  { id: "data", title: "Personal data we collect", body: <><p>The information depends on the Atlas features used and what your organisation provides. It may include:</p><ul><li><strong>Identity and work profile:</strong> name, profile image, employee identifier, job title, department, grade, team, manager, organisation and work location.</li><li><strong>Contact and account data:</strong> work email, phone number, username, authentication identifiers, account status and security logs.</li><li><strong>Learning records:</strong> courses, pathways, lesson progress, video completion, quiz answers, scores, attempts, assignments, feedback, learning hours, deadlines, certificates, badges and achievements.</li><li><strong>Content and communications:</strong> files, assignments, comments, support requests, feedback and organisation announcements.</li><li><strong>Technical data:</strong> IP address, browser, device, operating system, session activity, feature use, diagnostics and security events.</li><li><strong>Commercial data:</strong> customer contacts, orders, invoices, payment status and tax records. Complete card details are normally handled by an authorised payment provider.</li></ul><p>We may receive data from your organisation, authorised identity providers, connected workforce systems, payment providers and service providers that support Atlas.</p></> },
  { id: "sensitive", title: "Sensitive data and children", body: <><p>Atlas does not require sensitive personal data unless a particular authorised feature genuinely needs it and suitable safeguards are in place. Accessibility requests, uploaded assignments or programme demographics may sometimes reveal health, disability or other sensitive information. Do not place unnecessary sensitive or confidential information in free-text fields or uploads.</p><p>Atlas is intended primarily for adult professional users. An organisation must not provide children’s data unless the use is lawful, expressly agreed with Von Newman, properly authorised and supported by age-appropriate notices and safeguards.</p></> },
  { id: "use", title: "How and why we use data", body: <><p>We process personal data to provide accounts, authenticate users, deliver and recommend learning, record progress, administer assessments, issue certificates, send reminders, support organisation reporting, resolve support requests and keep Atlas reliable.</p><p>We also use data to protect accounts, investigate misuse, maintain audit logs, prevent assessment manipulation, comply with Nigerian law, administer contracts and improve usability and accessibility. Where reasonably possible, analytics and product improvement use aggregated or de-identified information.</p><p>Under the Nigeria Data Protection Act 2023, our lawful basis may be consent, performance of a contract, compliance with a legal obligation, protection of vital interests, performance of a task in the public interest, or another basis permitted by Nigerian law. An organisation that controls workforce-learning data is responsible for identifying its lawful basis.</p></> },
  { id: "visibility", title: "What organisation administrators can see", body: <><p>Authorised administrators, managers, instructors, assessors or compliance personnel may see information needed for their assigned role, including your profile, assigned learning, progress, attempts, scores, completion, overdue learning, certificates, assignments, feedback, achievements and relevant audit records.</p><p>Access is controlled by organisation settings and role permissions. Atlas should not be used as the sole basis for disciplinary, promotion, employment or other significant decisions without lawful authority, appropriate context and human review.</p></> },
  { id: "sharing", title: "When we share personal data", body: <><p>We do not sell personal data. We may share only what is reasonably necessary with:</p><ul><li>your organisation and its authorised representatives;</li><li>service providers supporting hosting, storage, authentication, email, security, analytics, support, content delivery, video, payments, document generation and certificate verification;</li><li>professional advisers such as lawyers, auditors, accountants and insurers;</li><li>Nigerian courts, regulators or law-enforcement bodies where disclosure is lawful and necessary; or</li><li>a successor in a genuine corporate transaction, subject to appropriate safeguards.</li></ul><p>Where a provider processes data outside Nigeria, we apply the transfer requirements and safeguards required by Nigerian law. We do not rely on foreign privacy regimes as the basis of this Nigeria-only policy.</p></> },
  { id: "retention", title: "Retention and account closure", body: <><p>We keep personal data only for as long as reasonably necessary for the purpose collected and for customer instructions, security, mandatory learning, certificate verification, legal claims, tax, accounting and regulatory obligations.</p><p>At the end of a customer relationship, customer data will be returned or deleted as provided in the contract and Data Processing Agreement, unless Nigerian law permits or requires further retention. Secure backups may retain data temporarily until their normal rotation ends. Properly de-identified information may be retained where it no longer identifies an individual.</p></> },
  { id: "security", title: "Security and data incidents", body: <><p>We use proportionate technical and organisational safeguards, including role-based access, authentication controls, encryption in transit and where appropriate at rest, logging, monitoring, secure development, vulnerability management, backups, confidentiality duties and incident response.</p><p>No system is completely secure. Users and organisations must protect credentials, configure appropriate permissions and tell us promptly about suspected misuse. If a personal-data breach occurs, we will assess it and notify affected customers, individuals or the Nigeria Data Protection Commission where Nigerian law requires.</p></> },
  { id: "rights", title: "Your rights under Nigerian law", body: <><p>Subject to the Nigeria Data Protection Act 2023 and applicable exceptions, you may request information about processing; access to your data; correction; deletion in appropriate cases; restriction; objection; data portability where applicable; withdrawal of consent; and a review of certain automated decisions. You may also object to direct marketing.</p><p>For an organisation-managed account, contact your organisation first. We will assist it with valid requests where required. For data controlled by Von Newman, email <a href="mailto:info@vonnewmanconsulting.com">info@vonnewmanconsulting.com</a>. We may verify your identity before responding.</p><p>If a concern is not resolved, you may lodge a complaint with the <a href="https://www.ndpc.gov.ng/" target="_blank" rel="noreferrer">Nigeria Data Protection Commission</a>.</p></> },
  { id: "automation", title: "Recommendations and automated features", body: <><p>Atlas may use configured rules to recommend learning, calculate progress, mark objective questions, determine completion, award achievements and identify overdue learning. These functions support learning administration and do not necessarily amount to a legally significant automated decision.</p><p>Customers must not use Atlas scores or recommendations for solely automated employment or similarly significant decisions unless they have a lawful basis, clear notice, suitable safeguards and any required human review.</p></> },
  { id: "cookies", title: "Cookies, communications and links", body: <><p>Atlas may use essential cookies and local storage to keep users signed in, maintain sessions, remember preferences and protect the service. Optional analytics cookies will be used only when Nigerian law requires and valid consent has been obtained. Browser settings can control cookies, but blocking essential cookies may stop Atlas from working correctly.</p><p>We may send necessary account, course, deadline, security, support, billing and policy messages. Permitted marketing can be stopped using its unsubscribe link or by contacting us. Third-party links and integrations are governed by their own notices.</p></> },
  { id: "changes", title: "Changes to this policy", body: <><p>We may update this policy when Atlas, our processing, providers, security practices or Nigerian legal requirements change. We will change the “Last updated” date and provide additional notice where a change materially affects your rights or where Nigerian law requires it.</p><p><strong>Last updated:</strong> 4 August 2026.</p></> },
];

export default function PrivacyPage() {
  return <LegalPage kind="Privacy Policy" title="Your learning data, handled with care." intro="A clear account of what Atlas collects, why it is needed, who can see it and the choices available to people using Atlas in Nigeria." summary="We collect only what is needed to run and protect Atlas, deliver learning, and give authorised organisations the records they need. We do not sell personal data." sections={sections}/>;
}
