import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "../ui/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service | Von Newman Atlas",
  description: "Terms governing use of Von Newman Atlas services in Nigeria.",
};

const sections: LegalSection[] = [
  { id: "agreement", title: "About these terms", body: <><p>These Terms govern access to and use of the Von Newman Atlas website, learning-management system, content-management system, course library, applications, support and related services (the “Services”) provided in Nigeria by <strong>Von Newman Technology Consultant Limited</strong> (“Von Newman”, “we”, “us” or “our”).</p><p>They apply to an organisation, company, public authority or institution that purchases or administers the Services (the “Customer”), and to its authorised learners, employees, contractors, administrators, instructors and other users (“Authorised Users”).</p><p>An accepted order form, proposal, statement of work, subscription agreement or Data Processing Agreement may also apply (an “Order”). If an Order conflicts with these Terms, the Order controls for that conflict.</p></> },
  { id: "acceptance", title: "Acceptance, authority and eligibility", body: <><p>By creating an account, accepting an Order, clicking an acceptance button or using the Services, you agree to these Terms and the policies incorporated into them. A person accepting for a Customer confirms that they have authority to bind it.</p><p>The Services are primarily for organisations and their professional personnel in Nigeria. Unless we agree otherwise in writing, they are not offered for personal household use or to children acting independently. A Customer must ensure that its users are eligible and that its workforce-learning activities are lawful.</p></> },
  { id: "accounts", title: "Accounts and administrators", body: <><p>Account information must be accurate and kept current. Credentials are personal and must not be shared, sold or made available to unauthorised persons. Suspected unauthorised access must be reported promptly to <a href="mailto:info@vonnewmanconsulting.com">info@vonnewmanconsulting.com</a>.</p><p>A Customer may appoint administrators who can create and deactivate accounts, import staff, assign roles and learning, configure access, view progress, export reports and manage the workspace. The Customer is responsible for its administrators, permissions and lawful use of workforce data. Authorised Users understand that their organisation may manage, export or delete workspace information subject to Nigerian law.</p></> },
  { id: "licence", title: "Licence and permitted use", body: <><p>Subject to these Terms, the applicable Order and payment of fees, Von Newman grants the Customer and its Authorised Users a limited, non-exclusive, non-transferable, non-sublicensable and revocable right to use Atlas during the agreed service period for lawful internal learning, training, development and compliance purposes.</p><p>No ownership rights are transferred. The Customer must remain within agreed user, organisation, storage, course and usage limits. Additional capacity may require a revised Order.</p></> },
  { id: "acceptable-use", title: "Acceptable use", body: <><p>You must not use Atlas to break Nigerian law or another person’s rights; upload malware or unlawful content; bypass security or access controls; scrape or extract data in bulk outside authorised features; reverse engineer the Services except where the law prevents that restriction; impersonate another person; interfere with assessments; falsify results or certificates; harass or unlawfully monitor a person; or build a competing service from Atlas without written permission.</p><p>We may investigate suspected misuse and may remove content, preserve relevant records, restrict access or cooperate with an affected Customer and Nigerian authorities where reasonably necessary and lawful.</p></> },
  { id: "customer", title: "Customer responsibilities", body: <><p>The Customer is responsible for configuring the Services, managing users and permissions, providing lawful instructions, ensuring Customer Data is accurate and lawful, giving required notices, maintaining its own devices and security, and using reports and learning outcomes responsibly.</p><p>Atlas must not be the sole basis for employment, disciplinary, promotion, safety-critical, regulated-profession or other high-impact decisions without appropriate human review. The Customer decides whether a course, assessment, learning record or certificate meets its own legal, professional or internal requirements.</p></> },
  { id: "learning", title: "Learning, assessments and certificates", body: <><p>Atlas may provide courses, pathways, lessons, quizzes, assignments, badges, achievements and certificates supplied by Von Newman, the Customer or third parties. Prerequisites, deadlines, passing scores, attempts, completion rules and certificate periods may be configured by the relevant owner or administrator.</p><p>We may correct clear errors, invalidate compromised attempts or require reassessment to protect assessment integrity. Unless expressly stated in writing, an Atlas certificate confirms only that the platform recorded satisfaction of the configured requirements. It is not by itself a degree, professional licence, government approval, employment guarantee or independently accredited qualification.</p><p>Certificates may be corrected, replaced, suspended, revoked or marked expired where issued in error, obtained through misconduct or subject to renewal.</p></> },
  { id: "data-content", title: "Customer Data and uploaded content", body: <><p>Customer Data includes account, learning and other information submitted to or generated through Atlas for a Customer. As between the parties, the Customer keeps its rights in Customer Data and permits Von Newman and its providers to process it only as reasonably needed to provide, secure, support and improve the Services, comply with Nigerian law and perform the agreement.</p><p>The Customer confirms it has the rights, notices and lawful bases needed for all submitted data. Users must not upload unnecessary personal data, confidential information they cannot disclose, security credentials, unlawful material or content that infringes another person’s rights.</p></> },
  { id: "privacy-ip", title: "Privacy, ownership and confidentiality", body: <><p>Personal data is handled under our <a href="/privacy">Privacy Policy</a>, the Nigeria Data Protection Act 2023 and any applicable Data Processing Agreement. Customers are responsible for workplace notices and proportionate use of employee learning data.</p><p>Von Newman and its licensors own Atlas software, interfaces, designs, workflows, databases, documentation, trademarks and Von Newman-created content. Customer-created courses remain owned by the Customer or their respective owners. Third-party content remains subject to its owner’s licence.</p><p>Each party must protect non-public business, security, technical, pricing and operational information received from the other and use it only for the agreement, except where disclosure is lawfully required.</p></> },
  { id: "fees", title: "Fees, taxes and payment", body: <><p>Fees, billing cycles, limits, renewal terms and payment dates are stated in the applicable Order. Unless stated otherwise, fees exclude applicable Nigerian taxes and levies, which the Customer is responsible for other than taxes on Von Newman’s net income.</p><p>Undisputed overdue amounts may result in lawful interest, collection costs, restriction or suspension after any notice required by the Order or Nigerian law. Fees are non-cancellable and non-refundable except where an Order or applicable Nigerian law says otherwise.</p></> },
  { id: "service", title: "Availability, support and third parties", body: <><p>We use commercially reasonable efforts to provide Atlas but cannot promise uninterrupted, error-free or completely secure operation. Maintenance, updates, internet conditions, provider failures, security events or circumstances outside reasonable control may affect availability. Specific uptime, support or service-credit commitments apply only when written in an Order.</p><p>We may update Atlas for functionality, performance, security or legal compliance. Third-party identity, video, payment, communication and content services have their own terms, availability and privacy practices. The Customer is responsible for authorising integrations.</p></> },
  { id: "suspension", title: "Suspension and termination", body: <><p>We may suspend access where reasonably necessary for a material breach, non-payment, unlawful use, security risk, harm to others, a Nigerian legal requirement or cessation of business. Where practical and lawful, we will provide notice and an opportunity to remedy; urgent risks may require immediate action.</p><p>Subscription, renewal and termination rights are set out in the Order. If no cure period is stated, a material breach may be terminated if not cured within 30 days after written notice. When the agreement ends, access ceases and the Customer should export permitted data. Data is then handled under the Order, Data Processing Agreement, retention policy and Nigerian law.</p></> },
  { id: "warranties", title: "Warranties and disclaimers", body: <><p>Each party confirms it has authority to enter the agreement. For paid Services, we will provide Atlas with reasonable skill and care and substantially in accordance with applicable documentation.</p><p>To the fullest extent allowed by Nigerian law, and except for that express commitment, the Services and content are provided “as is” and “as available”. Atlas is a learning platform and does not provide legal, employment, regulatory, medical, financial or other professional advice. Course content does not replace qualified advice where it is required.</p></> },
  { id: "liability", title: "Liability and indemnity", body: <><p>Nothing in these Terms excludes liability that Nigerian law does not permit us to exclude, including fraud or fraudulent misrepresentation. To the fullest lawful extent, neither party is liable for indirect, incidental, special or consequential loss, or lost profit, revenue, business, savings, goodwill or data.</p><p>Unless an Order provides a different negotiated cap, each party’s total aggregate liability relating to the Services in any 12-month period will not exceed fees paid or payable for the affected Services in that period.</p><p>The Customer will indemnify Von Newman against third-party claims arising from unlawful Customer Data, unlawful instructions, the Customer’s breach of law or misuse by its users, except to the extent caused by Von Newman’s breach, negligence or wilful misconduct.</p></> },
  { id: "law", title: "Nigerian law and disputes", body: <><p>These Terms and the Services are governed by the laws of the Federal Republic of Nigeria. The parties will first give written notice of a dispute and allow authorised representatives at least 30 days to attempt a good-faith resolution, unless urgent protective relief is needed.</p><p>If the dispute is not resolved, the courts of competent jurisdiction in Lagos State, Nigeria will have jurisdiction. Mandatory rights and remedies under Nigerian law, including applicable consumer protections, remain unaffected.</p></> },
  { id: "general", title: "Changes and general terms", body: <><p>We may update these Terms for changes in Atlas, Nigerian law, security practices or business operations. We will state the new effective date and give reasonable notice of material changes affecting a current paid subscription unless an urgent legal or security change is required.</p><p>These Terms do not create a partnership, employment or agency relationship. Neither party is liable for delay caused by events beyond reasonable control. Failure to enforce a right is not a waiver. If a provision is unenforceable, it will be adjusted only as necessary and the rest will continue. These Terms, the Order and incorporated policies form the agreement about the Services. Electronic acceptance and signatures may be used as permitted by Nigerian law.</p><p><strong>Effective date:</strong> 4 August 2026.</p></> },
];

export default function TermsPage() {
  return <LegalPage kind="Terms of Service" title="A clear agreement for using Atlas." intro="The rules that keep Atlas useful, secure and fair for organisations and their authorised learners in Nigeria." summary="Atlas is a business learning platform. Customers manage authorised users and learning decisions; Von Newman provides, protects and supports the service under these terms." sections={sections}/>;
}
