"use client";

import { useState } from "react";
import { Check, Plus, ShieldCheck, Trash2, X } from "lucide-react";
import type { AtlasAssessment, AtlasQuestion } from "./atlas-store";

function blankQuestion(assessment:AtlasAssessment,index:number):AtlasQuestion {
  return {id:`${assessment.id}-q-${Date.now()}-${index}`,prompt:"New question",options:["Correct answer","Alternative answer","Another alternative","Not applicable"],answer:0,feedback:"Explain why the correct answer is the strongest choice."};
}

export function AssessmentEditor({assessment,onClose,onSave,onRemove}:{assessment:AtlasAssessment;onClose:()=>void;onSave:(assessment:AtlasAssessment)=>void;onRemove:()=>void}) {
  const [draft,setDraft]=useState(()=>structuredClone(assessment));
  const patch=(next:Partial<AtlasAssessment>)=>setDraft(current=>({...current,...next}));
  const patchQuestion=(index:number,next:Partial<AtlasQuestion>)=>patch({questions:draft.questions.map((question,i)=>i===index?{...question,...next}:question)});
  const addQuestion=()=>patch({questions:[...draft.questions,blankQuestion(draft,draft.questions.length+1)],questionsShown:draft.questions.length+1});
  const removeQuestion=(index:number)=>{const questions=draft.questions.filter((_,i)=>i!==index);patch({questions,questionsShown:Math.min(draft.questionsShown,questions.length)});};
  return <div className="assessment-editor-backdrop" onMouseDown={onClose}><section className="assessment-editor" onMouseDown={event=>event.stopPropagation()}>
    <header><span><ShieldCheck/></span><div><small>{draft.kind.toUpperCase()}</small><h2>Configure assessment</h2><p>{draft.kind==="Knowledge check"?"Attached to one lesson and required before it can be completed.":draft.kind==="Module quiz"?"Unlocks after every required lesson and lesson check in this module is complete.":"Unlocks after every required module quiz has been passed."}</p></div><button aria-label="Close assessment editor" onClick={onClose}><X/></button></header>
    <div className="assessment-editor-body">
      <aside><label>Title<input value={draft.title} onChange={event=>patch({title:event.target.value})}/></label><label>Instructions<textarea value={draft.instructions} onChange={event=>patch({instructions:event.target.value})}/></label><div className="assessment-settings"><label>Pass mark<div><input min={0} max={100} type="number" value={draft.passMark} onChange={event=>patch({passMark:+event.target.value})}/><span>%</span></div></label><label>Attempts<input min={1} type="number" value={draft.attempts} onChange={event=>patch({attempts:+event.target.value})}/></label><label>Questions shown<input min={1} max={draft.questions.length} type="number" value={draft.questionsShown} onChange={event=>patch({questionsShown:Math.min(+event.target.value,draft.questions.length)})}/></label><label>Time limit<input min={1} type="number" value={draft.timeLimit} onChange={event=>patch({timeLimit:+event.target.value})}/></label></div><label className="editor-toggle"><input type="checkbox" checked={draft.required} onChange={event=>patch({required:event.target.checked})}/><span><b>Required assessment</b><small>Blocks the next learning stage until passed</small></span></label><label className="editor-toggle"><input type="checkbox" checked={draft.randomise} onChange={event=>patch({randomise:event.target.checked})}/><span><b>Randomise questions</b><small>Present a different order for each attempt</small></span></label><label>Feedback timing<select value={draft.feedbackMode} onChange={event=>patch({feedbackMode:event.target.value as AtlasAssessment["feedbackMode"]})}><option>After submission</option><option>Immediate</option></select></label></aside>
      <main><div className="assessment-question-heading"><div><small>QUESTION SET</small><h3>{draft.questions.length} authored questions</h3></div><button onClick={addQuestion}><Plus/> Add question</button></div>{draft.questions.map((question,index)=><article className="assessment-question-card" key={question.id}><header><span>{String(index+1).padStart(2,"0")}</span><label>Question prompt<textarea value={question.prompt} onChange={event=>patchQuestion(index,{prompt:event.target.value})}/></label><button aria-label={`Delete question ${index+1}`} onClick={()=>removeQuestion(index)}><Trash2/></button></header><div className="assessment-options">{question.options.map((option,optionIndex)=><label className={question.answer===optionIndex?"correct":""} key={optionIndex}><input type="radio" name={`answer-${question.id}`} checked={question.answer===optionIndex} onChange={()=>patchQuestion(index,{answer:optionIndex})}/><span>{String.fromCharCode(65+optionIndex)}</span><input aria-label={`Option ${String.fromCharCode(65+optionIndex)}`} value={option} onChange={event=>patchQuestion(index,{options:question.options.map((item,i)=>i===optionIndex?event.target.value:item)})}/>{question.answer===optionIndex&&<Check/>}</label>)}</div><label className="assessment-feedback">Answer feedback<input value={question.feedback||""} onChange={event=>patchQuestion(index,{feedback:event.target.value})}/></label></article>)}</main>
    </div>
    <footer><button className="remove-assessment" onClick={onRemove}><Trash2/> Remove assessment</button><span>Changes remain in the course draft until you save or publish.</span><button className="save-assessment" disabled={!draft.questions.length||!draft.title.trim()} onClick={()=>onSave(draft)}>Save assessment <Check/></button></footer>
  </section></div>;
}
