"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, ChevronDown, CirclePlay, Eye, FileText, GripVertical, Library, Link2, MonitorPlay, Palette, Play, Plus, Save, Settings, ShieldCheck, Sparkles, Trash2, Upload, Users, X } from "lucide-react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";
import type { AtlasCourse, AtlasLesson, AtlasModule } from "./atlas-store";

gsap.registerPlugin(ScrollTrigger, useGSAP);

export type MediaAsset = {
  id:string; title:string; type:"Video"|"Document"|"Audio"|"Image"; meta:string;
  color:string; status:"Approved"|"Processing"|"Needs attention"; usage:number;
  transcript?:boolean; thumbnail?:string;
};

export const mediaAssets:MediaAsset[]=[
  {id:"media-ai-framework",title:"Responsible AI: decision framework",type:"Video",meta:"08:42 · English · Captions included",color:"#dcd5ff",status:"Approved",usage:3,transcript:true},
  {id:"media-frontline",title:"Frontline Excellence: moments that matter",type:"Video",meta:"12:18 · English · Transcript ready",color:"#cceffc",status:"Approved",usage:6,transcript:true},
  {id:"media-state",title:"Understanding the Nigerian State",type:"Video",meta:"16:06 · English · Captions included",color:"#ffe6ad",status:"Approved",usage:4,transcript:true},
  {id:"media-citizen",title:"Citizen journey mapping workshop",type:"Video",meta:"24:35 · English · Transcript ready",color:"#ffd9e8",status:"Approved",usage:2,transcript:true},
  {id:"media-workbook",title:"Citizen journey mapping workbook",type:"Document",meta:"PDF · 1.2 MB · English",color:"#d5f7d9",status:"Approved",usage:6},
  {id:"media-data-clinic",title:"Data clinic recording — July",type:"Video",meta:"44:18 · Transcript missing",color:"#f2dcff",status:"Needs attention",usage:1},
];

const MEDIA_KEY="atlas-media-assets-v1";
function readMedia(){if(typeof window==="undefined")return mediaAssets;try{return [...JSON.parse(localStorage.getItem(MEDIA_KEY)||"[]") as MediaAsset[],...mediaAssets]}catch{return mediaAssets}}
function useMediaLibrary(){const [assets,setAssets]=useState<MediaAsset[]>(mediaAssets);useEffect(()=>{const sync=()=>setAssets(readMedia());
  // Hydrate the browser-only prototype media store after the server render.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setAssets(readMedia());window.addEventListener("atlas-media-change",sync);return()=>window.removeEventListener("atlas-media-change",sync)},[]);return assets}
function saveUploadedAsset(asset:MediaAsset){const custom=readMedia().filter(item=>!mediaAssets.some(base=>base.id===item.id));localStorage.setItem(MEDIA_KEY,JSON.stringify([asset,...custom]));window.dispatchEvent(new Event("atlas-media-change"))}
function mediaTitle(id?:string){return id?readMedia().find(asset=>asset.id===id)?.title:""}

export function MediaGallery({onUpload}:{onUpload:()=>void}) {
  const root=useRef<HTMLDivElement>(null);
  const fileInput=useRef<HTMLInputElement>(null);
  const assets=useMediaLibrary();
  const [query,setQuery]=useState("");
  const [type,setType]=useState("All");
  const [selected,setSelected]=useState(mediaAssets[0]);
  const visible=assets.filter(asset=>(type==="All"||asset.type===type)&&asset.title.toLowerCase().includes(query.toLowerCase()));
  const upload=(file?:File)=>{if(!file)return;const kind=file.type.startsWith("video/")?"Video":file.type.startsWith("audio/")?"Audio":file.type.startsWith("image/")?"Image":"Document";const asset:MediaAsset={id:`media-${Date.now()}`,title:file.name.replace(/\.[^.]+$/,""),type:kind,meta:`${kind==="Video"?"Processing duration":`${Math.max(.1,file.size/1024/1024).toFixed(1)} MB`} · Uploaded just now`,color:"#e6e1ff",status:"Processing",usage:0};saveUploadedAsset(asset);setSelected(asset);onUpload()};
  useGSAP(()=>{
    const cards=root.current?.querySelectorAll(".media-gallery-card");
    if(!cards?.length)return;
    gsap.from(cards,{y:24,autoAlpha:0,duration:.5,stagger:.07,ease:"power3.out"});
  },{scope:root,dependencies:[type],revertOnUpdate:true});
  return <section ref={root} className="media-library-page"><input ref={fileInput} hidden type="file" accept="video/*,audio/*,image/*,.pdf,.ppt,.pptx" onChange={e=>upload(e.target.files?.[0])}/><div className="cms-heading"><div><span className="today">Atlas CMS · Reusable assets</span><h1>Media</h1><p>Upload, preview and govern the videos and resources used throughout Atlas courses.</p></div><button className="button button-primary" onClick={()=>fileInput.current?.click()}><Upload/> Upload media</button></div><div className="media-library-toolbar"><label><Library/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search videos, documents, owners or tags"/></label><div>{["All","Video","Document","Audio","Image"].map(item=><button className={type===item?"active":""} onClick={()=>setType(item)} key={item}>{item}</button>)}</div></div><div className="media-gallery-layout"><div className="media-gallery">{visible.map(asset=><button key={asset.id} onClick={()=>setSelected(asset)} className={`media-gallery-card ${selected.id===asset.id?"selected":""}`}><span className="media-thumb" style={{background:asset.color}}>{asset.type==="Video"?<><Play/><i>{asset.meta.split(" · ")[0]}</i></>:<FileText/>}</span><div><small>{asset.type} · {asset.status}</small><h3>{asset.title}</h3><p>{asset.meta}</p><em>Used in {asset.usage} courses</em></div></button>)}</div><aside className="media-inspector"><span className="media-thumb large" style={{background:selected.color}}>{selected.type==="Video"?<Play/>:<FileText/>}</span><small>SELECTED ASSET · {selected.status}</small><h2>{selected.title}</h2><p>{selected.meta}</p><div><span><b>{selected.usage}</b><small>courses using asset</small></span><span><b>{selected.transcript?"Ready":"Review"}</b><small>accessibility</small></span></div><h3>Used by courses</h3>{["AI for Smarter Public Service","Frontline Excellence","Service Design for Everyone"].slice(0,Math.min(3,selected.usage)).map(item=><button key={item}>{item}<ArrowRight/></button>)}<button className="button button-primary"><Settings/> Edit asset & versions</button></aside></div></section>
}

const sections=[
  ["Overview",BookOpen],["Appearance",Palette],["Curriculum",Library],["Assessment",ShieldCheck],
  ["Completion",CheckCircle2],["Certificate",Sparkles],["Access",Users],["Preview",Eye],["Review & publish",MonitorPlay],
] as const;
const palettes=[
  ["#dcd5ff","#5b43d6"],["#cceffc","#087ca7"],["#ffe6ad","#b65b00"],
  ["#ffd9e8","#a92c62"],["#d5f7d9","#238d4c"],["#f2dcff","#7b35ae"],
];

function blankCourse():AtlasCourse {
  const stamp=Date.now();
  return {id:`course-${stamp}`,code:`CUSTOM-${String(stamp).slice(-4)}`,title:"Untitled course",description:"Write a clear promise for the learner.",category:"Public Service",collection:"Public sector",level:"Foundation",color:"#dcd5ff",accent:"#5b43d6",progress:0,duration:"Self-paced",modules:1,status:"Available",art:"✦",instructor:"Ifeoma Kalu",organisation:"Federal Service",published:false,learners:0,pathCode:"PUB-01",pathTitle:"Public Administration Foundations",audience:"Federal Service learners",curriculum:[{code:"M1",title:"Start here",description:"Introduce the capability and its relevance.",required:true,lessons:[]}],lifecycle:"Draft",updatedAt:new Date().toISOString().slice(0,10),fullDescription:"",secondaryCategories:[],skills:[],objectives:["Apply the capability confidently at work"],language:"English (Nigeria)",completionRule:"Complete all required lessons and pass the final assessment",certificateEnabled:true,version:"0.1"};
}

export function CourseStudio({course,onClose,onSave,onPublish}:{course:AtlasCourse|null;onClose:()=>void;onSave:(course:AtlasCourse)=>void;onPublish:(course:AtlasCourse)=>void}) {
  const root=useRef<HTMLDivElement>(null);
  const [draft,setDraft]=useState<AtlasCourse>(()=>course?structuredClone(course):blankCourse());
  const [section,setSection]=useState("Overview");
  const [selectedLesson,setSelectedLesson]=useState<{module:number;lesson:number}|null>(null);
  const [mediaOpen,setMediaOpen]=useState(false);
  const [notice,setNotice]=useState("");
  const lessonCount=draft.curriculum.reduce((sum,module)=>sum+module.lessons.length,0);
  const readiness=[draft.title!=="Untitled course",draft.description.length>10,lessonCount>0,draft.curriculum.every(module=>module.lessons.every(lesson=>lesson.type)),draft.objectives?.length,draft.organisation].filter(Boolean).length;
  useEffect(()=>{window.scrollTo({top:0,behavior:"auto"})},[]);
  const patch=(next:Partial<AtlasCourse>)=>setDraft(current=>({...current,...next,updatedAt:new Date().toISOString().slice(0,10)}));
  const flash=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(""),1800)};
  useGSAP(()=>{
    const mm=gsap.matchMedia();
    mm.add("(prefers-reduced-motion: no-preference)",()=>{
      gsap.from(".studio-main > *",{y:22,autoAlpha:0,duration:.45,stagger:.055,ease:"power3.out"});
      ScrollTrigger.batch(".studio-reveal",{start:"clamp(top 90%)",once:true,onEnter:batch=>gsap.fromTo(batch,{y:34,autoAlpha:0},{y:0,autoAlpha:1,duration:.55,stagger:.06,ease:"power3.out"})});
    });
    return()=>mm.revert();
  },{scope:root,dependencies:[section],revertOnUpdate:true});
  const save=()=>{onSave({...draft,published:false,lifecycle:"Draft"});flash("Draft saved")};
  const selectMedia=(asset:MediaAsset)=>{
    if(selectedLesson)setDraft(current=>({...current,curriculum:current.curriculum.map((module,mi)=>mi===selectedLesson.module?{...module,lessons:module.lessons.map((lesson,li)=>li===selectedLesson.lesson?{...lesson,type:asset.type==="Video"?"Video":"Document",mediaId:asset.id,duration:asset.meta.split(" · ")[0]}:lesson)}:module)}));
    else patch({introMediaId:asset.id});
    setMediaOpen(false);flash(`${asset.title} linked`);
  };
  return <div ref={root} className="course-studio">
    {notice&&<div className="action-toast"><CheckCircle2/>{notice}</div>}
    <header className="studio-header"><button onClick={onClose}><ArrowLeft/> Courses</button><div><small>{course?"EDITING COURSE":"NEW COURSE"} · {draft.code}</small><input aria-label="Course title" value={draft.title} onChange={e=>patch({title:e.target.value})}/><span><i/> {draft.lifecycle} · Version {draft.version||"1.0"} · Autosaved just now</span></div><div><button className="button button-white" onClick={save}><Save/> Save draft</button><button className="button button-primary" onClick={()=>setSection("Review & publish")}>Review course <ArrowRight/></button></div></header>
    <div className="studio-layout">
      <aside className="studio-nav"><strong>COURSE STUDIO</strong>{sections.map(([label,Icon])=><button key={label} className={section===label?"active":""} onClick={()=>setSection(label)}><Icon/>{label}{label==="Curriculum"&&<em>{lessonCount}</em>}</button>)}<div className="studio-health"><span>{readiness}/6 ready</span><div><i style={{width:`${readiness/6*100}%`}}/></div><small>Atlas checks structure, media, access and learner readiness.</small></div></aside>
      <main className="studio-main">
        {section==="Overview"&&<><StudioHeading kicker="COURSE FOUNDATION" title="Shape the promise, audience and outcome." body="These details power catalogue discovery, the LMS course page and reporting."/><div className="overview-workspace studio-reveal"><div className="studio-form two"><label>Short description<textarea value={draft.description} onChange={e=>patch({description:e.target.value})}/><small>{draft.description.length}/180 characters</small></label><label>Full description<textarea value={draft.fullDescription||""} onChange={e=>patch({fullDescription:e.target.value})} placeholder="Explain the context, value and learning experience."/><small>Shown on the learner course overview</small></label><label>Primary category<select value={draft.category} onChange={e=>patch({category:e.target.value})}><option>Public Service</option><option>Leadership and Management</option><option>Data and Analytics</option><option>AI & Emerging Technology</option><option>Cybersecurity and IT</option></select></label><label>Difficulty<select value={draft.level} onChange={e=>patch({level:e.target.value as AtlasCourse["level"]})}><option>Foundation</option><option>Intermediate</option><option>Advanced</option></select></label><label>Target audience<input value={draft.audience} onChange={e=>patch({audience:e.target.value})}/></label><label>Instructor<input value={draft.instructor} onChange={e=>patch({instructor:e.target.value})}/></label><label>Language<select value={draft.language} onChange={e=>patch({language:e.target.value})}><option>English (Nigeria)</option><option>French</option><option>Hausa</option></select></label><label>Learning objective<input value={draft.objectives?.[0]||""} onChange={e=>patch({objectives:[e.target.value]})} placeholder="Learners will be able to…"/></label></div><aside className="overview-guidance"><span><Sparkles/></span><small>LEARNER PROMISE</small><h3>{draft.title}</h3><p>{draft.description}</p><div><b>{draft.level}</b><b>{draft.language}</b></div><ul><li className={draft.description.length>40?"done":""}>Clear value proposition</li><li className={draft.audience.length>8?"done":""}>Defined audience</li><li className={draft.objectives?.[0]?"done":""}>Measurable objective</li></ul></aside></div></>}
        {section==="Appearance"&&<><StudioHeading kicker="LMS APPEARANCE" title="Design how learners meet this course." body="Choose the card background, accent and introductory media, with a live learner preview."/><div className="appearance-grid studio-reveal"><section><h3>Course palette</h3><div className="palette-grid">{palettes.map(([color,accent])=><button aria-label={`Use ${color}`} className={draft.color===color?"active":""} key={color} style={{background:color,color:accent}} onClick={()=>patch({color,accent})}><Check/></button>)}</div><label>Course symbol<input maxLength={2} value={draft.art} onChange={e=>patch({art:e.target.value})}/></label><button className="asset-select" onClick={()=>{setSelectedLesson(null);setMediaOpen(true)}}><CirclePlay/><span><b>{mediaTitle(draft.introMediaId)||"Choose introductory video"}</b><small>Select an approved asset from Media</small></span><ChevronDown/></button></section><CoursePreview course={draft}/></div></>}
        {section==="Curriculum"&&<CurriculumEditor draft={draft} setDraft={setDraft} onMedia={(module,lesson)=>{setSelectedLesson({module,lesson});setMediaOpen(true)}}/>}
        {section==="Assessment"&&<><StudioHeading kicker="ASSESSMENT" title="Check for genuine understanding." body="Select a governed question bank and configure a fair final assessment."/><div className="assessment-workspace studio-reveal"><section className="studio-card"><label className="toggle-line"><span><b>Require final assessment</b><small>Learners must pass to complete this course.</small></span><input type="checkbox" defaultChecked/></label><div className="studio-form three"><label>Question bank<select><option>Public Service foundations</option><option>Responsible AI foundations</option><option>Data literacy scenarios</option></select></label><label>Pass mark<div className="input-suffix"><input type="number" defaultValue="80"/><span>%</span></div></label><label>Attempts<input type="number" defaultValue="2"/></label><label>Questions shown<input type="number" defaultValue="10"/></label><label>Time limit<select><option>20 minutes</option><option>30 minutes</option><option>No limit</option></select></label><label>Question order<select><option>Randomised per learner</option><option>Fixed sequence</option></select></label></div></section><aside className="assessment-summary"><span><ShieldCheck/></span><small>DELIVERY SUMMARY</small><h3>10 questions</h3><p>Randomised from 48 approved questions across six learning objectives.</p><div><b>80%</b><small>pass mark</small></div><div><b>2</b><small>attempts</small></div><button onClick={()=>flash("Assessment preview opened")}>Preview assessment <ArrowRight/></button></aside></div></>}
        {section==="Completion"&&<><StudioHeading kicker="COMPLETION LOGIC" title="Define what completion actually means." body="Atlas uses meaningful activity—not page visits—to calculate learner progress."/><div className="completion-workspace studio-reveal"><div className="studio-card rules-list">{["Complete every required lesson","Watch at least 80% of each required video","Pass the final assessment","Submit required practical activities"].map((rule,i)=><label key={rule}><input type="checkbox" defaultChecked={i<3}/><span><b>{rule}</b><small>{i===1?"Prevents skipping through video learning.":"Included in the course completion calculation."}</small></span><em>{i<3?"Required":"Optional"}</em></label>)}</div><aside className="completion-summary"><small>COURSE COMPLETES WHEN</small><strong>3</strong><h3>required conditions are met</h3><p>Progress updates from lesson engagement, video watch events and the final assessment result.</p><div><span>Lessons</span><b>100%</b></div><div><span>Video threshold</span><b>80%</b></div><div><span>Pass mark</span><b>80%</b></div></aside></div></>}
        {section==="Certificate"&&<><StudioHeading kicker="VERIFIED CREDENTIAL" title="Connect completion to a trusted certificate." body="Choose the template, issuer, validity and verification requirements."/><div className="certificate-workspace studio-reveal"><div className="studio-card studio-form two"><label>Certificate template<select><option>Federal Service completion certificate</option><option>Professional pathway certificate</option></select></label><label>Validity<select><option>12 months</option><option>24 months</option><option>Does not expire</option></select></label><label>Issuer<input defaultValue="Federal Service Learning Directorate"/></label><label>Signatories<input defaultValue="Course instructor · Learning director"/></label><label className="toggle-line compact"><span><b>Public verification</b><small>Allow certificate ID verification</small></span><input type="checkbox" defaultChecked/></label><label className="toggle-line compact"><span><b>Renewal reminder</b><small>Notify learner 30 days before expiry</small></span><input type="checkbox" defaultChecked/></label></div><aside className="certificate-mini" style={{background:draft.color,color:draft.accent}}><Sparkles/><small>CERTIFICATE OF COMPLETION</small><h3>Amara Okafor</h3><p>has successfully completed</p><h4>{draft.title}</h4><div><span>Issued on completion</span><b>Verified credential</b></div></aside></div></>}
        {section==="Access"&&<><StudioHeading kicker="DISTRIBUTION" title="Put the course in the right hands." body="Control organisation, audience and the way this learning appears in the LMS."/><div className="access-workspace studio-reveal"><div className="studio-card studio-form two"><label>Organisation<select value={draft.organisation} onChange={e=>patch({organisation:e.target.value})}><option>Federal Service</option><option>All organisations</option><option>Atlas Professional Academy</option></select></label><label>Access type<select value={draft.status} onChange={e=>patch({status:e.target.value as AtlasCourse["status"]})}><option>Available</option><option>Assigned</option><option>Mandatory</option><option>Recommended</option></select></label><label>Audience<select><option>Entire organisation</option><option>Digital Services department</option><option>Policy and planning roles</option><option>Selected cohort</option></select></label><label>Availability<select><option>Immediately after publication</option><option>Schedule a date</option></select></label></div><aside className="reach-summary"><span><Users/></span><small>ESTIMATED REACH</small><strong>{draft.status==="Mandatory"?"2,480":"428"}</strong><h3>eligible learners</h3><p>{draft.status==="Mandatory"?"Placed directly in every learner’s required learning list.":"Visible to permitted learners in the organisation catalogue."}</p><div><CheckCircle2/> Federal Service access configured</div><div><CheckCircle2/> LMS visibility rules ready</div></aside></div></>}
        {section==="Preview"&&<><StudioHeading kicker="LEARNER PREVIEW" title="Inspect the experience before release." body="The preview uses the same course data and visual language as the LMS."/><CoursePreview course={draft} large/></>}
        {section==="Review & publish"&&<><StudioHeading kicker="GOVERNANCE" title="Move the course into controlled publication." body="Resolve readiness items, save a draft, or submit the complete experience for publication."/><div className="publish-workspace studio-reveal"><section><h3>Readiness check</h3>{[["Course identity",draft.title!=="Untitled course"],["Learning objectives",Boolean(draft.objectives?.length)],["Curriculum contains lessons",lessonCount>0],["Every lesson has a type",draft.curriculum.every(m=>m.lessons.every(l=>l.type))],["Organisation access",Boolean(draft.organisation)],["Certificate configured",draft.certificateEnabled!==false]].map(([label,ready])=><p key={String(label)} className={ready?"ready":""}>{ready?<CheckCircle2/>:<Settings/>}<span><b>{label}</b><small>{ready?"Ready for review":"Needs attention before publishing"}</small></span></p>)}</section><aside><span>{readiness}/6</span><h3>{readiness===6?"Ready to publish":"Course needs attention"}</h3><p>Publishing makes the saved course immediately available to its configured audience in the LMS prototype.</p><button className="button button-white" onClick={save}>Save draft</button><button className="button button-primary" disabled={readiness<6} onClick={()=>onPublish({...draft,published:true,lifecycle:"Published",version:draft.version==="0.1"?"1.0":draft.version})}>Publish course <ArrowRight/></button></aside></div></>}
      </main>
    </div>
    {mediaOpen&&<MediaPicker selected={selectedLesson?draft.curriculum[selectedLesson.module]?.lessons[selectedLesson.lesson]?.mediaId:draft.introMediaId} onClose={()=>setMediaOpen(false)} onSelect={selectMedia}/>}
  </div>;
}

function StudioHeading({kicker,title,body}:{kicker:string;title:string;body:string}){return <header className="studio-heading"><span>{kicker}</span><h1>{title}</h1><p>{body}</p></header>}

function CoursePreview({course,large=false}:{course:AtlasCourse;large?:boolean}) {
  return <article className={`studio-course-preview ${large?"large":""}`} style={{background:course.color,color:course.accent}}><div><small>{course.category}</small><span>{course.art}</span></div><h2>{course.title}</h2><p>{course.description}</p><div><span>{course.level}</span><span>{course.curriculum.reduce((sum,m)=>sum+m.lessons.length,0)} lessons</span><span>{course.duration}</span></div><button>View course <ArrowRight/></button></article>
}

function CurriculumEditor({draft,setDraft,onMedia}:{draft:AtlasCourse;setDraft:React.Dispatch<React.SetStateAction<AtlasCourse>>;onMedia:(module:number,lesson:number)=>void}) {
  const addModule=()=>setDraft(c=>({...c,curriculum:[...c.curriculum,{code:`M${c.curriculum.length+1}`,title:`New module ${c.curriculum.length+1}`,description:"",objective:"",required:true,lessons:[]}]}));
  const updateModule=(mi:number,next:Partial<AtlasModule>)=>setDraft(c=>({...c,curriculum:c.curriculum.map((m,i)=>i===mi?{...m,...next}:m)}));
  const addLesson=(mi:number)=>setDraft(c=>({...c,curriculum:c.curriculum.map((m,i)=>i===mi?{...m,lessons:[...m.lessons,{code:`${m.code}.${m.lessons.length+1}`,title:`New lesson ${m.lessons.length+1}`,type:"Video",required:true,completionRule:"Watch 80% of the video"}]}:m)}));
  const updateLesson=(mi:number,li:number,next:Partial<AtlasLesson>)=>setDraft(c=>({...c,curriculum:c.curriculum.map((m,i)=>i===mi?{...m,lessons:m.lessons.map((l,j)=>j===li?{...l,...next}:l)}:m)}));
  return <><StudioHeading kicker="CURRICULUM" title="Build the learner’s journey." body="Modules contain authored lessons. Video and document lessons select governed assets from the Media library."/><div className="curriculum-studio">{draft.curriculum.map((module,mi)=><section className="module-studio studio-reveal" key={module.code}><header><GripVertical/><span>{String(mi+1).padStart(2,"0")}</span><div><input value={module.title} onChange={e=>updateModule(mi,{title:e.target.value})}/><textarea value={module.description||""} onChange={e=>updateModule(mi,{description:e.target.value})} placeholder="Module description and context"/></div><button onClick={()=>setDraft(c=>({...c,curriculum:c.curriculum.filter((_,i)=>i!==mi)}))}><Trash2/></button></header><div className="module-objective"><label>Module objective<input value={module.objective||""} onChange={e=>updateModule(mi,{objective:e.target.value})} placeholder="What will learners be able to do?"/></label><label><input type="checkbox" checked={module.required!==false} onChange={e=>updateModule(mi,{required:e.target.checked})}/> Required module</label></div><div className="studio-lessons">{module.lessons.map((lesson,li)=><article key={lesson.code}><span>{li+1}</span><div><input value={lesson.title} onChange={e=>updateLesson(mi,li,{title:e.target.value})}/><div><select value={lesson.type||"Video"} onChange={e=>updateLesson(mi,li,{type:e.target.value as AtlasLesson["type"]})}><option>Video</option><option>Text</option><option>Document</option><option>Audio</option><option>Scenario</option><option>Activity</option></select><button onClick={()=>onMedia(mi,li)}><Link2/>{mediaTitle(lesson.mediaId)||"Choose from Media"}</button><select value={lesson.completionRule||""} onChange={e=>updateLesson(mi,li,{completionRule:e.target.value})}><option>Watch 80% of the video</option><option>Mark complete manually</option><option>Pass lesson activity</option><option>Open required resource</option></select></div></div><button onClick={()=>updateModule(mi,{lessons:module.lessons.filter((_,i)=>i!==li)})}><X/></button></article>)}<button className="add-lesson" onClick={()=>addLesson(mi)}><Plus/> Add lesson</button></div></section>)}<button className="add-module" onClick={addModule}><Plus/> Add module</button></div></>
}

function MediaPicker({selected,onClose,onSelect}:{selected?:string;onClose:()=>void;onSelect:(asset:MediaAsset)=>void}) {
  const [query,setQuery]=useState("");
  const assets=useMediaLibrary();
  const visible=useMemo(()=>assets.filter(asset=>asset.title.toLowerCase().includes(query.toLowerCase())),[assets,query]);
  return <div className="media-drawer-backdrop" onMouseDown={onClose}><aside className="media-drawer" onMouseDown={e=>e.stopPropagation()}><header><div><small>ATLAS MEDIA LIBRARY</small><h2>Choose a reusable asset</h2></div><button onClick={onClose}><X/></button></header><label className="drawer-search"><Library/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search approved videos and resources"/></label><div className="drawer-assets">{visible.map(asset=><button key={asset.id} className={selected===asset.id?"selected":""} onClick={()=>onSelect(asset)}><span style={{background:asset.color}}>{asset.type==="Video"?<Play/>:<FileText/>}</span><div><small>{asset.type} · {asset.status}</small><b>{asset.title}</b><p>{asset.meta}</p><em>Used in {asset.usage} courses</em></div>{selected===asset.id&&<CheckCircle2/>}</button>)}</div><footer><button className="button button-white"><Upload/> Upload new asset</button><small>New uploads are added to Media and can be reused across courses.</small></footer></aside></div>
}
